### PR TITLE
Handle db errors gracefully during scan

### PR DESCRIPTION
**Pull request by eherget**

### CODE REVIEW

**Comment by eherget** [comment]
This will need to be updated once PR # 507 is merged.

**Comment by eherget** [comment]
This has been updated following PR # 507 merge and pylint fixes are in place.  It is ready for review and merging.

**Comment by jdobes** [comment]
there seems to be new conflicts cased by #510

**Comment by jdobes** [comment]
please rebase the `reposcan/database/package_store.py` file

**Comment by eherget** [comment]
The conflict should be resolved now.

**Pull request merged**
