### PR TITLE
Fixed requests including ^ and ~ in nevra

### PR DESCRIPTION
**Pull request by Josca**

### CODE REVIEW

**Comment by eherget** [comment]
Looks good and it works.  merging

**Comment by eherget** [comment]
Hold on... looking into why some checks were not successful.  I see ocdeployer command timed out waiting for dc/vmaas-apispec to be ready.  I don't know enough about our apispec usage now... is it trying to build spec from our newly changed handler definitions?  I'm pinging @jdobes on IRC to find out.

**Comment by eherget** [comment]
run tests

**Comment by psegedy** [comment]
for some reason `"vmaas-apidoc-1-deploy" has gone missing` :confused: 
```
4:39:35 PM | vmaas-apidoc | Deployment Config | Warning | Failed | Deployer pod "vmaas-apidoc-1-deploy" has gone missing
-- | -- | -- | -- | -- | --
4:36:42 PM | vmaas-apidoc | Deployment Config | Normal | Deployment Created | Created new replication controller "vmaas-apidoc-1" for version 1
```
anyway, `run tests` comment to rerun test is no longer working. You need to trigger it from Jenkins

**Comment by eherget** [comment]
tests passed this time.  merging...

**Pull request merged**
