### PR TITLE
feat(reposcan): add CSAF sync task

### PR DESCRIPTION
**Pull request by michalslomczynski**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by psegedy** [comment]
Tests are failing because sync now takes too long and also the local development with docker-compose will be harder because you'd need to wait at least an hour for the sync.
I'd suggest to do something similar as we are doing with OVAL and repolists. Let's add modified changes.csv (e.g. only with 2023 cves) and jsons referenced in changes.csv to https://github.com/RedHatInsights/vmaas-data. Then we can set env to point to vmaas-data repo and download files from there. The env would need to be set in reposcan.env and in app-interface vmaas ephemeral deploy target.
@mtclinton what do you think?
@michalslomczynski would you mind doing that?

**Comment by michalslomczynski** [comment]
Will do, thanks for proposing resolution.

**Comment by mtclinton** [comment]
yes, I like this solution :)

**Review by jdobes — APPROVED** [review]

**Pull request merged**
