### PR TITLE
Make updates api db query more efficient

### PR DESCRIPTION
**Pull request by eherget**
This changes the updates api to do a single db query where it used to do one db query per package specified in the request.  This implementation does the evr comparison in the python/webapp code.  The rpmver_array() and other evr related functions and types are no longer required in the database.

In my tests, what used to take 22 seconds now takes 15 with this change.

### CODE REVIEW

**Comment by eherget** [comment]
I need to add that I did not remove the mentioned evr functions and types defined in the database.  Should we accept this change, that can be a follow up issue/pr

**Comment by ggainey** [comment]
So was doing some before/after comparisons with this code, and I noticed one thing - pre-change, NEVRA rpcbind-**0.2.0-13.el6_9.1**.x86_64 finds no available-updates; post-change, it finds rpcbind-**0.2.0-13.el6_9**.x86_64 . Clearly this is an edge case, but I'm not sure which one is correct - Eric, could you take a look at this?

**Comment by eherget** [comment]
I will take a look at this rpcbind example issue

**Comment by eherget** [comment]
Good catch, ggainey.  My logic was incorrect when comparing a value from one evr to a null from the other (9.1 v 9, for example, the '1' on the left is greater than the non-existent corresponding value on the right)

This is now fixed and this PR can be accepted once ginrag completes his review.

**Comment by grinrag** [comment]
@eherget I tested the changes. So far I see a difference in the answers produced by webapp based on `RedHatInsights:master`  and webapp based on `eherget:efficient-updates-db-queries`.

I tested on this input:
[pack.txt](https://github.com/RedHatInsights/vmaas/files/2013152/pack.txt)

I see performance improve:
`0.647s` against `1.150s`

**Pull request merged**
