### PR TITLE
VMAAS-1377: respect module requires

### PR DESCRIPTION
**Pull request by MichaelMraka**

### CODE REVIEW

**Review by jdobes — CHANGES_REQUESTED** [review]
`module_stream_require` table is referencing `module_stream` table, references from this table need to be removed when calling reposcan API for deleting content sets

see delete_content_set function in vmaas/reposcan/database/repository_store.py

**Comment by MichaelMraka** [comment]
stream requires removal fixed

**Review by jdobes — APPROVED** [review]

**Pull request merged**
