### PR TITLE
use centos/rhel containers for all services

### PR DESCRIPTION
**Pull request by jdobes**

### CODE REVIEW

**Comment by ggainey** [comment]
Trying to build/test using docker-compose, I am running into problems.

First : 
```
vmaas-reposcan     |     basePath="/api/v1",
vmaas-reposcan     | TypeError: __init__() missing 1 required positional argument: 'openapi_version'
vmaas-reposcan     | Everything is up - executing command
vmaas-reposcan     | Traceback (most recent call last):
vmaas-reposcan     |   File "/reposcan/reposcan.py", line 16, in <module>
vmaas-reposcan     |     from apidoc import SPEC, VMAAS_VERSION, setup_apispec
vmaas-reposcan     |   File "/reposcan/apidoc.py", line 15, in <module>
vmaas-reposcan     |     basePath="/api/v1",
```

Discussion w/ @tkasparek suggests this is because the pip-install version of apispec is expecting more than the (older) rpm-installed version did - see  https://github.com/RedHatInsights/vulnerability-engine/pull/164/files#diff-bfe8715226c07a4576fe37c53eeb37ccR25 , for example.

Second : 
Addressing the above by adding `+    openapi_version='2.0',` gets us past the initial failure, but we immediately hit a new one:
```
vmaas-reposcan     | Everything is up - executing command
vmaas-reposcan     | Traceback (most recent call last):
vmaas-reposcan     |   File "/reposcan/reposcan.py", line 16, in <module>
vmaas-reposcan     |     from apidoc import SPEC, VMAAS_VERSION, setup_apispec
vmaas-reposcan     |   File "/reposcan/apidoc.py", line 16, in <module>
vmaas-reposcan     |     basePath="/api/v1",
vmaas-reposcan     |   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/apispec/core.py", line 240, in __init__
vmaas-reposcan     |     plugin.init_spec(self)
vmaas-reposcan     | AttributeError: 'str' object has no attribute 'init_spec'
```

Needs more investigation and fixing, looks like.

**Comment by ggainey** [comment]
CHANGELOG.rst from https://github.com/marshmallow-code/apispec shows that 1.0 introduced A LOT of breaking-changes - and that's what we're getting when we pip-install.

**Comment by jdobes** [comment]
I've updated the PR, could you re-check again, please?

**Comment by ggainey** [comment]
I added a commit to restore psycopg2-binary to webapp, since it fails without it, and merged manually. Closing, thanks for the work!

**Pull request closed without merging**
