### PR TITLE
Reposcan refactoring

### LINKED ISSUE #22: reposcan: support removal of data
- add support for removal of previously synced repository
- add support for clearing DB at once (maybe, it can be done by removing DB container as well)
- add automatic removal of redundant rows (packages/evr/errata that are not part of any repositories anymore)

### LINKED ISSUE #293: /api/v1/sync doesn't support adding new repos
we have a `/api/v1/sync` API to sync all repos + cves using single API but it's not possible to pass a repository list using POST here - to do this it's needed to call `/api/v1/sync/repo`. This makes confusion like #276, let's improve it somehow.

### PR DESCRIPTION
**Pull request by jdobes**
- fixes #22 
- fixes #293
- export API endpoint renamed (it's not sync)
- repository import and repository sync are now two separate steps
- fixed bug when repositories with empty basearch or releasever were ignored
- added support for removing repositories (using content sets labels)
- added support to get status and to cancel currently running background task
- all API endpoints changing database changed from GET to PUT

### CODE REVIEW

**Comment by jdobes** [comment]
last pylint commit not related to my changes, need to investigate later

**Comment by ggainey** [comment]
While I'm testing functionality - shouldn't these be reached as api/v2 ? Since they're a pretty big change to the currently-published API?

**Comment by jdobes** [comment]
- fixed TypeError
- added task type info to /task/status response

**Comment by ggainey** [comment]
APISpec for DELETE /repos/{repo} is Worng (but the functionality looks good!)

**Comment by ggainey** [comment]
github had Problems today. It appears that the rebase-and-merge worked - master looks good - but the PR didn't hear about it, and is now complaining about merge-conflicts (because it's conflicting with itself now, essentially)

Closing the PR, as master seems to have the right thing - but will check closely for problems.

**Pull request closed without merging**
