### PR TITLE
feat(csaf): load csaf dump in webapp

### PR DESCRIPTION
**Pull request by psegedy**
RHINENG-9212

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by jdobes — APPROVED** [review]
ok

**Review by michalslomczynski — APPROVED** [review]

**Comment by psegedy** [comment]
need to split it into 2 PRs, otherwise we won't be able to export the correct dump before deploying webapp

**Pull request merged**
