### PR TITLE
Jenkins automation

### PR DESCRIPTION
**Pull request by psegedy**
It is needed to have Jenkinsfile with defined pipeline in this repo. Jenkins will automatically search for Jenkinsfile and run tests for every pull request.
Dockerfile-qe is needed to run webapp container without running the application. Application wil be triggered from jenkins pipeline and run using `coverage.py` to collect coverage of `app.py`.

Steps of pipeline:
- Install necessary packages
- deploy vmaas to insights-dev cluster
- run app using coverage run ..., setup db, run tests
- collect coverage
- publish results to polarion and publish HTML coverage and test results

@mkoura could you also look at it, please?

### CODE REVIEW

**Comment by ggainey** [comment]
> Deployment to openshift (and all following stages) failed because it tries to find `Dockerfile-qe` in master.

So you're thinking that as soon as we merge, it'll be fine?

**Comment by psegedy** [comment]
I wanted to say yes... but now I'm thinking that building from `master` branch is a bad idea. It has to be built from branch that PR was created or from locally merged PR with master. I need to figure out if there is such option using https://github.com/RedHatInsights/e2e-deploy

**Comment by ggainey** [comment]
@psegedy it sounds like this needs some more work on your side, yes? Will wait till y'all tell me you're happy with it before I move forward here

**Comment by mkoura** [comment]
@psegedy is this ready? Can you please rebase it?

**Comment by ggainey** [comment]
@psegedy  - are we ready to merge this? or is there more work incoming?

**Comment by psegedy** [comment]
@ggainey It's ready, you can merge this

**Pull request merged**
