### PR TITLE
Add support for Prometheus monitoring to webapp

### PR DESCRIPTION
**Pull request by ggainey**

### CODE REVIEW

**Comment by ggainey** [comment]
DO NOT MERGE - needs additional work

**Comment by ggainey** [comment]
With second commit, this is now complete - removing WIP from title :)

**Comment by ggainey** [comment]
BaseHandler adds instrumentation to count calls to each subclass (CveAPI ErrataAPI PackagesAPI RepoAP UpdatesAPI). Histogram added for calls to /updates. 

Results available via `curl -X GET http://<VMAAS-SYSTEM>:8080/metrics`

**Comment by tkasparek** [comment]
Does not break existing functionality + /metrics enpoint returns some data (however I have no clue how to interpret them whether they're sane or not).

**Pull request merged**
